### ISSUE TITLE
3.	Σύνδεση με εφαρμογή παρατηρήσεων – alerts (Η.Μαγκλογιάννης)

### ISSUE THREAD

**Issue by larjohn** [eHIF/eHIFDemo#3]

**Comment by larjohn** [comment]
@Thanos400 έχουμε κάτι συγκεκριμένο εδώ;

**Comment by Thanos400** [comment]
Επικοινώνισα με τον Ηλία. Η εφαρμογή τους θα ειναι αυτόνομη οποτε δουλεύουν ανεξάρτητα. Δεν μου εδωσε πλάνο ολοκλήρωσης.
