### ISSUE TITLE
Δεν είναι διαθέσιμες οι διαδικασίες για τους χρήστες 

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#36]
Προσπάθησα να ξεκινήσω μια διαδικασία από το  menu "Διαδικασίες eHif" και δεν μπορώ καθώς δεν είναι καμία διαθέσιμη (χρήστες iatros, nosokomos). Μήπως γίνονται αλλαγές και δεν είναι διαθέσιμες προς το παρόν;

**Comment by larjohn** [comment]
Εγώ βλέπω:

D1_1 
KY_D2_1 

για το νοσοκόμο

**Comment by kalkal1** [comment]
Όντως, για τον νοσοκόμο υπάρχει, για τον γιατρό δεν βλέπουμε διαθέσιμες διαδικασίες (iatros)

**Comment by larjohn** [comment]
Διότι δε μπορεί να ξεκινήσει διαδικασίες ο γιατρός, προτού γίνει επίσκεψη
