### ISSUE TITLE
Καρτέλα Ασθενείς, Ενημέρωση στοιχείων ασθενούς:

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#38]
a.	Υπάρχει πρόβλημα στο ημερολόγιο της επιλογής ημερομηνία γέννησης. Δεν εμφανίζει έτος, δεν μπορώ να επιλέξω ημερομηνία και δεν μπορώ να πάω προς τα πίσω.

**Comment by larjohn** [comment]
Μπορείς να δώσεις link?

**Comment by kalkal1** [comment]
Κέντρο Υγείας/ Ασθενείς/Καλλιόπη Καλαντζάκη/Επεξεργασία/
http://147.102.33.146/eHIFDemo/public/patients/22/edit
(login iatros). 
Ο χρήστης δημιουργήθηκε κατά την διαδικασία εισαγωγή ασθενούς. Το πρόβλημα είναι πως αν εγώ έχω γεννηθεί το 1980 δεν μπορώ εύκολα να πάω από το 2015 στο 1980 με αυτό το ημερολόγιο. Επίσης, σε αυτόν τον χρήστη δεν μπορώ να επιλέξω μια ημερομηνία, δεν με αφήνει. Μονάχα αν την δώσω εγώ εκτός χωρίς να χρησιμοποιήσω το ημερολόγιο.

**Comment by glivanos** [comment]
http://147.102.33.146/eHIFDemo/public/bpmn/runtime/D1_1:1:7504/usertask4/23290
Ως μια προσθήκη για τον έλεγχο στοιχείων.θα πρέπει να ενσωματωθεί κι ο έλεγχος του πεδίου έτος γέννησης (στο παράδειγμα αυτό έδωσα τιμή 2018, η οποί έγινε δεκτή). Ο έλεγχος για το ΑΜΚΑ (στο παράδειγμα πεδίο ΑΣΦΑΛΙΣΤΙΚΟ ΤΑΜΕΙΟ) λειτουργεί ως προς την απάιτηση για πληκτρολόγηση 11 αριθμητικών ψηφίων, δε γίνεται όμως έλεγχος για ταυτοποίηση με το ονοματεπώνυμο. Πληκτρολόγησα ένα νέο ονοματεπώνυμο αλλά ως ΑΣΦΑΛΙΣΤΙΚΟ ΤΑΜΕΙΟ έδωσα ένα ήδη υπάρχον και η διαδικασία ολοκληρώθηκε. Από τον έλεγχο στη βάση των ασθενών, παρατήρησα ότι για το ΑΜΚΑ που πληκτρολόγησα, η αρχική εγγραφή αντικαταστάθηκε από το νέο ονοματεπώνυμο που εισήγαγα, άρα "σβήστηκε" μια καταχώρυση ασθενούς.

**Comment by larjohn** [comment]
Σχετικά με την επιλογή ημερομηνίας, ποιον περιηγητή χρησιμοποιείτε; Πάντως, για να επιλέξετε γρήγορα μια ημερομηνία μπορείτε να κάνετε κλικ στο έτος όπου θα δείτε να αλλάζει η προβολή της επιλογής και θα μπορέσετε να μεταβείτε γρηγορότερα στο 1980, για παράδειγμα.

Η επικύρωση των πεδίων είναι ακόμα σε στάδιο ανάπτυξης και ίσως να μην είναι διαθέσιμη κατά την πιλοτική, αφού είναι εκτός των στόχων της.

**Comment by kalkal1** [comment]
Οκ, τώρα είδα πως δουλεύει, μια χαρά παίρνει την ημερομηνία που του δίνουμε. Παρ' όλα αυτά, η ημερομηνία που καταχωρείται στην βάση δεν είναι αυτή που του έδωσα. Μόλις εισήγαγα τον ασθενή kal kal και ενώ πήρε την ημερομηνία κατά το τρέξιμο της διαδικασίας "εισαγωγή ασθενούς", στην βάση δεν έχει καταχωρηθεί σωστά η ημερομηνία γέννησης αλλά το 000-00-00. Εγώ χρησιμοποιώ firefox.

**Comment by larjohn** [comment]
Η ημερομηνία καταχωρείται στη μορφή 2015-03-03.

Για να μην είναι αυτό στην ευθύνη του χρήστη, πρέπει να διορθωθεί το #37
