### ISSUE TITLE
Καρτέλα Έλεγχος αποθεμάτων

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#39]
Καρτέλα Έλεγχος αποθεμάτων, Δήλωση χαμηλού αποθέματος, Έλεγχος ελλείψεων, Συμπλήρωση φόρμας παραγγελίας:
a.	Τα στοιχεία ασθενούς πρέπει να ανασύρονται με κάποιον τρόπο από την βάση με τους ασθενείς, να μην δίνει τα στοιχεία αυτά ο χρήστης.
b.	Στο τέλος της διαδικασίας για την παραγγελία φαρμακευτικού υλικού πού καταχωρούνται οι πληροφορίες για το απόθεμα, την παραγγελία κλπ;
c.	Αν επιλέξω την KY_D2_1/Έλεγχος αποθεμάτων/επάρκεια φαρμακευτικού υλικού και μετά την παραγγελία, δεν φαίνεται κανένα απόθεμα.

**Comment by larjohn** [comment]
Οι διαδικασίες 2.* και 3.* έχει αποφασιστεί να μην έχουν αντίκρυσμα στη βάση δεδομένων, παρά μόνο να υπάρχουν ως επίδειξη, λόγω της εμβέλειας του έργου.
