### ISSUE TITLE
Διαθέσιμες Διαδικασίες και Ενεργές Διαδικασίες

### ISSUE THREAD

**Issue by beieka** [eHIF/eHIFDemo#42]
1) Δεν δίνεται η πλήρης λίστα των διαθέσιμων διαδικασιών (πιθανά θα έπρεπε να δίνονται όλες και να υπάρχει ένας τρόπος επισήμανσης για τις διαδικασίες που είναι ενεργές για κάθε χρήστη), 
2) Δεν δίνεται η δυνατότητα στον χρήστη να εκκινήσει διαδικασία από το παράθυρο διαθέσιμες διαδικασίες, και 
2) Επιτρέπεται στον χρήστη να εκκινήσει μια διαδικασία που έχει "αναρτηθεί" στο παράθυρο ενεργές διαδικασίες (πιθανά από ημιτελή χρήση άλλου χρήστη) χωρίς να μπορεί να επαναλάβει την ίδια διαδικασία.

**Comment by larjohn** [comment]
1) Για ποιο λόγο να γνωρίζει κάποιος τις διαδικασίες που δεν τον αφορούν; Ποιες διαδικασίες θα έπρεπε να φαίνονται;

2) Σε ποιον χρήστη αναφέρεστε;

3) Ουσιαστικά συνεχίζει μια διαδικασία που ξεκίνησε άλλος χρήστης και πλέον ανήκει στην αρμοδιότητά του. Εννοείται κάτι άλλο;

**Comment by beieka** [comment]
1) Θεωρώ ότι ένα λειτουργικό σύστημα θα πρέπει να δίνει μια εποπτική εικόνα για τις δυνατότητες που παρέχει. Άρα, θα πρέπει να είναι ορατές όλες οι διαδικασίες, επιτρέποντας κάθε φορά την προσβασιμότητα αποκλειστικά σ' έναν (π.χ. ιατρό) ή ενδεχομένως σε περισσότερους χρήστες (π.χ. ιατρό, νοσηλευτή).

2) Αναφέρομαι στον χρήστη Ιατρό.

3) Ακριβώς σ' αυτό αναφέρομαι. Δεν θα έπρεπε να μπορώ να ξεκινήσω εκ νέου μια διαδικασία?? Σ' ένα Κέντρο Υγείας μπορεί να δραστηριοποιούνται περισσότεροι από έναν ιατροί. Δεν θα μπορούν να ενεργήσουν ο ένας ανεξάρτητα από τον άλλο??

**Comment by larjohn** [comment]
1) Οι διαδικασίες του πακέτου 1 γενικά δεν είναι ορατές πέραν από την 1.1 διότι δεν είναι καν εκκινήσιμες, αφού αποτελούν ακολουθία της 1.1. 

2) Ο Ιατρός δε μπορεί να εκκινήσει διαδικασία για το λόγο που αναφέρθηκε στο 1)

3) Για την εκκίνηση μιας νέας διαδικασίας, πάμε πάλι στη λίστα με τις διαδικασίες. Για να συνεχίσει πχ ο γιατρός μια διαδικασία, πρέπει να έχει προηγουμένως εκκινηθεί από κάποιον νοσηλευτή.
