### ISSUE TITLE
Ο ιατρός καταγράφει τα ευρήματα της εξέτασης

### ISSUE THREAD

**Issue by beieka** [eHIF/eHIFDemo#43]
Στον κατάλογο ευρήματα, υπάρχουν και ονομασίες χημικών ενώσεων, όπως αυτό της οργανικής χημικής ένωσης 2-προπανόλη. 
Ο λόγος που αναφέρονται σ' αυτή την λίστα είναι λόγω πιθανού ατυχήματος/δηλητηρίασης (π.χ. κατάποση, εισπνοή) από αυτούς τους βλαπτικούς παράγοντες??

**Comment by larjohn** [comment]
Ναι:

http://www.galinos.gr/web/drugs/main/icdcodes/t51.2#content
