### ISSUE TITLE
Καταχώρηση ασθενούς - Ασθενής - Ενημέρωση στοιχείων ασθενούς

### ISSUE THREAD

**Issue by beieka** [eHIF/eHIFDemo#45]
Στο πεδίο Ημερομηνία γέννησης, δεν είναι ενεργό το ημερολόγιο.
Γι' αυτό τον λόγο συμπλήρωσα την ημερομηνία ως εξής: 18-11-1967

Μετά από αυτό η καρτέλα Ασθενής είχε τα ακόλουθα στοιχεία:

Κατερίνα Μπέη του Σπυρίδων
0000-00-00 (2015 ετών) !!!!!!!!!!!!!
ΑΜΚΑ: 356509368
Διεύθυνση: Κουνουπιδιανά, Ακρωτήρι Χανίων
Τηλέφωνο: 28210 73100

Κατά την Ενημέρωση στοιχείων ασθενούς, το ημερολόγιο είναι ενεργό, χωρίς ωστόσο να μπορεί ο χρήστης να επιλέξει την κατάλληλη ημερομηνία.

**Comment by larjohn** [comment]
Σε ποια σελίδα αναφέρεστε;
