### ISSUE TITLE
Συνεδρίες με τον Ιατρό/Αποτελέσματα Συνεδρίας

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#46]
i.	Στο πεδίο εξετάσεις αν πατήσουμε προσθήκη δεν αποθηκεύεται τίποτα.
ii.	Στο πεδίο φαρμακευτική αγωγή το κουμπί Προσθήκη δεν λειτουργεί
iii.	Οι λίστες στα Θεραπευτικές ενέργειες και Νοσηλεία δεν εμφανίζονται
iv.    Αν πατήσουμε Αποθήκευση εμφανίζεται σφάλμα
V.     Αν πατήσουμε Ακύρωση εμφανίζεται η σελίδα Συνεδρία.
	Σε αυτήν την σελίδα (συνεδρία) δεν εμφανίζονται όλα στα ελληνικά.
	1) Εμφανίζεται ένα πεδίο id, return to all sessions. 
        2) Αν πατήσω ακύρωση εμφανίζεται σφάλμα

**Comment by larjohn** [comment]
Είναι υπό ανάπτυξη
