### ISSUE TITLE
Δημιουργία φακέλου από τον ιατρό

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#47]
Server error response [url] http://ws307.math.auth.gr:8080/activiti-rest/service/form/form-data?taskId=58125 [status code] 500 [reason phrase] Internal Server Error 

url: http://vp.med.auth.gr/eHIFDemo/public/bpmn/runtime/D1_3:1:61222/usertask2/58125

Διαδικασία: D1_3 (58115): Δημιουργία φακέλου από τον ιατρό

**Comment by larjohn** [comment]
Έχουμε αλλάξει διεύθυνση: 

http://147.102.33.146/eHIFDemo/public
