### ISSUE TITLE
Ταξινόμηση περιστατικού από νοσηλευτή

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#48]
url error: http://vp.med.auth.gr/eHIFDemo/public/bpmn/runtime/D1_2:1:61217/usertask1/61298

Server error response [url] http://ws307.math.auth.gr:8080/activiti-rest/service/form/form-data?taskId=61298 [status code] 500 [reason phrase] Internal Server Error 

Διαδικασία:  D1_2 (61294): Ταξινόμηση περιστατικού από το νοσηλευτή

**Comment by larjohn** [comment]
http://147.102.33.146/eHIFDemo/public
