### ISSUE TITLE
Καταχώρηση νέου ραντεβού - Κατάλογος Ραντεβού

### ISSUE THREAD

**Issue by beieka** [eHIF/eHIFDemo#49]
Καρτέλα Καταχώρηση νέου ραντεβού:
Στο πεδίο καταχώρησης της ημερομηνίας ακολουθείται το αγγλικό πρότυπο?? 
Έτος-Μήνας-Ημέρα ??
Ο χρήστης δεν μπορεί να καταχωρήσει την ημερομηνία 
είτε ως 25 Φεβρουαρίου 2015, είτε ως 25-02-2015.
Η καταχώρηση γίνεται μόνο όταν δοθεί ως: 2015-02-25

Καρτέλα Κατάλογος Ραντεβού:
Αυτή η καρτέλα θα συμπληρωθεί:
α) με ημερήσια/εβδομαδιαία λίστα των ραντεβού όλων των ασθενών ??
β) με λίστα των ραντεβού (π.χ. εβδομαδιαία, μηνιαία/τρίμηνη παρακολούθηση) κάθε ασθενούς ??

Η Καρτέλα Κατάλογος Ραντεβού δεν δίνει την δυνατότητα στον χρήστη:
α) επιστροφής στο κεντρικό μενού ή 
β) πιθανής επιλογής ενός συγκεκριμένου ασθενούς για αναζήτηση/"διάβασμα" του ιατρικού του φακέλου (σε περίπτωση ύπαρξής του).

**Comment by larjohn** [comment]
Τα ραντεβού είναι υπό ανάπτυξη

**Comment by larjohn** [comment]
Υλοποιήθηκε
