### ISSUE TITLE
Διαχείριση φαρμακευτικών αποθεμάτων

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#50]
Η διαδικασία αυτή μήπως πρέπει να αφορά στη μαζική παραγγελία σκευασμάτων; Όταν επιλέχθηκε "Ανάγκη προμήθειας φαρμακευτικού υλικού" στη φόρμα παραγγελίας ζητήθηκε το όνομα του ασθενή για τον οποίο θα χρησιμοποιηθεί το σκεύασμα. Αυτό θα ισχύει για κάθε ασθενή ο οποίος χρειάζεται φάρμακα; Αν ναι, μήπως είναι αρκετά χρονοβόρο να καταγράφεται όλη αυτή η διαδικασία ή αυτή η καταγραφή να τηρείται για τα "ακριβά" σκευάσματα;

**Comment by larjohn** [comment]
@Thanos400 ?

**Comment by glivanos** [comment]
Επισυνάπτω το σύνδεσμο ενός παραδείγματος:
http://147.102.33.146/eHIFDemo/public/bpmn/runtime/KY_D2_1:1:20004/usertask9/23245

**Comment by Thanos400** [comment]
Νομίζω οτι ο σκοπός της διαδικασίας ειναι να διατηρούνται καποια φαρμακα σε stock στο ΚΥ. Απο τις συνεντεύξεις ειχαμε καταγράψει την διαδικασία η οποία και εκτελούνταν σε περιοδική βάση (πχ. μια φορά τον μήνα). Σε αυτή την περίπτωση δεν χρειαζεται να αναφέρεται ο ασθενής που θα το χρησιμοποιήσει. 
Στην περίπτωση που αναφερόμαστε σε μεμονωμένα φάρμακα, που συνήθως ειναι και ακριβά, τοτε θα μπορούσε να περιγράφεται και για ποιον ασθενή παραγγέλνεται. Ισως αυτό θα πρέπει να αποτελέι εξαίρεση και οχι ο κανόνας στις παραγγελίες.
