### ISSUE TITLE
Ο ασθενής οδηγείται στον εξεταστικό θάλαμο του Κέντρου Υγείας 

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#51]
url error: http://vp.med.auth.gr/eHIFDemo/public/bpmn/runtime/D1_4:1:61227/usertask6/58133

Server error response [url] http://ws307.math.auth.gr:8080/activiti-rest/service/form/form-data?taskId=58133 [status code] 500 [reason phrase] Internal Server Error 

Διαδικασία: D1_4 (58127): ο ασθενής οδηγείται στον εξεταστικό θάλαμο του Κέντρου Υγείας

**Comment by larjohn** [comment]
http://147.102.33.146/eHIFDemo/public
