### ISSUE TITLE
Νοσηλευτές D1_1: Καρτέλα - Τα στοιχεία τα δίνει ο συνοδός

### ISSUE THREAD

**Issue by beieka** [eHIF/eHIFDemo#52]
Καρτέλα: Τα στοιχεία τα δίνει ο συνοδός
Κατά την επιλογή του ονόματος του ασθενούς εμφανίζονται επιτυχώς όλα τα στοιχεία της εγγραφής του.
Ωστόσο, στο πεδίο Ασφαλιστικό ταμείο εμφανίζεται ο αριθμός του ΑΜΚΑ που δόθηκε από τον χρήστη (356509368), τον οποίο δεν δέχεται ως σωστό για να μπορέσει να προχωρήσει στο Επόμενο βήμα.
Εμφανίζεται η ένδειξη: Please match the requested format για το συγκεκριμένο πεδίο. 
Όταν το πεδίο συμπληρωθεί  με 1111111111 τότε μπορεί ο χρήστης να προχωρήσει στο Επόμενο βήμα.

**Comment by larjohn** [comment]
Το ΑΜΚΑ είναι από ότι ξέρω 11ψήφιο. Η εισαγωγή του 9ψήφιου είχε γίνει όταν δεν υπήρχε η επικύρωση. Μπορείτε να το αλλάξετε στην επεξεργασία του ασθενούς και να το ελέγξετε πάλι;
