### ISSUE TITLE
έλεγχος δικαιωμάτων χρήστη

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#53]
Ίσως κάποια από τα bugs ή από τα εμφανιζόμενα λάθη κατά την επεξεργασία να οφείλονται στην ταυτόχρονη επεξεργασία διαδικασιών από άτομα που έχουν εισέλθει στο σύστημα με το ίδιο όνομα και κωδικό χρήστη. Τι θα συμβεί αν σε δύο τερματικά ο ίδιος χρήστη εκτελεί την ίδια διαδικασία ή συνεχίζει μια ενεργή διαδικασία (ανταγωνίζεται χρονικά μεταξύ των δύο τερματικών;);Οπότε χρειάζεται να καθοριστεί το πλαίσιο δικαιωμάτων και κανόνων εισόδου και χρήση της εφαρμογής από το προσωπικό.

**Comment by larjohn** [comment]
Τυπικά δεν υπάρχει ανταγωνισμός. Αν ο χρήστης σκόπιμα βρεθεί στο ίδιο σημείο σε δύο τερματικά, τότε η δεύτερη υποβολή του ίδιου task θα έχει ως αποτέλεσμα σιωπηρό σφάλμα και θα τον οδηγήσει στην λίστα των διεργασιών.

**Comment by glivanos** [comment]
Ευχαριστώ!Ένα δεύτερο θέμα που παρατήρησα είναι το εξής:
Στη νέα πλατφόρμα (http://147.102.33.146/eHIFDemo/public/users/login), δοκίμασα να ανοίξω τέσσερις διαφορετικές καρτέλες (login ως iatros, nosokomos, grammateas, dioikisi ξεχωριστά σε κάθε καρτέλα) στον φυλλομετρητή ενός μόνο τερματικού για να παρατηρήσω τι διαφορετικό θα "έβλεπε" κάθε εργαζόμενος. Μετά από μερικά δευτερόλεπτα όλες οι καρτέλες ανανεώθηκαν στο λογαριασμό σύνδεσης της καρτέλας που άνοιξα τελευταία (login ως dioikisi εν προκειμένω). Αυτό μάλλον προϋποθέτει ότι κάθε κατηγορία εργαζόμενου χρειάζεται να εκτελεί τις διαδικασίες σε ξεχωριστό τερματικό (επομένως χρειάζονται τουλάχιστον τέσσερα τερματικά) ή να γίνεται αποσύνδεση του ενός χρήστη και είσοδος του επόμενου. Αυτό ίσως χρειάζεται μια ιδιαίτερη αντιμετώπιση.

**Comment by larjohn** [comment]
Δυστυχώς δεν μπορεί να αντιμετωπιστεί με τα υπάρχοντα τεχνικά μέσα. Εάν θέλετε να συνδεθείτε στην ίδια σελίδα με διαφορετικούς λογαριασμούς, θα χρειαστεί να την επισκεφθείτε από άλλο περιηγητή. Το ίδιο ισχύει και σε οποιαδήποτε άλλη σελίδα, πχ το ίδιο το github
