### ISSUE TITLE
Έγκριση διοικητικής υπηρεσίας 

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#54]
Για τη διαδικασία προκήρυξης διαγωνσιμού αλλά και γενικά για τις διαδικασίας διοικητικής δραστηριότητας πού μπορεί ο χρήστης να δει τις εγγραφές, τα αποτελέσματα και να ανατρέξει σε αρχείο καταγραφών; Προβλέπεται να διαμορφώνεται αυτόματα ένα έγγραφο προς εκτύπωση κι υπογραφή βάσει κάποιου προτύπου το οποίο θα λαμβάνει τα στοιχεία από τη φόρμα καταχώρισης;

**Comment by larjohn** [comment]
Οι διοικητικές διαδικασίες δεν θα υποστηριχθούν από την εφαρμογή, πέραν από την επίδειξη της εκτέλεσής τους.
