### ISSUE TITLE
Ο ιατρός του Κέντρου Υγείας συνδέεται με τα στοιχεία του στην υπηρεσία ηλεκτρονικής συνταγογράφησης 

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#55]
url error: http://vp.med.auth.gr/eHIFDemo/public/bpmn/runtime/D1_10:1:61260/usertask1/80410

Server error response [url] http://ws307.math.auth.gr:8080/activiti-rest/service/form/form-data?taskId=80410 [status code] 500 [reason phrase] Internal Server Error 

Διαδικασία: D1_10 (80404): Ο ιατρός του Κέντρου Υγείας συνδέεται με τα στοιχεία του στην υπηρεσία ηλεκτρονικής συνταγογράφησης

**Comment by larjohn** [comment]
http://147.102.33.146/eHIFDemo/public
