### ISSUE TITLE
Χρήστης διαχειριστή

### ISSUE THREAD

**Issue by glivanos** [eHIF/eHIFDemo#56]
Για τις διεργασίες που "φαίνονται" ενεργές αλλά είναι ανολοκλήρωτες λόγω εμφάνισης λάθους, μήπως θα έπρεπε να υπάρχει ένας λογαριασμός superuser ή τεχνικού διαχειριστή, μέσω του οποίου μόνο ο εξειδικευμένος υπεύθυνος για την τεχνική υποστήριξη να μπορεί να διορθώνει τα λάθη ή να "διαγράφει" τις συγκεκριμένες διαδικασίες από τη σχετική λίστα.

**Comment by larjohn** [comment]
Στο http://147.102.33.146/eHIFDemo/public υποστηρίζεται η ακύρωση των διαδικασιών
