### ISSUE TITLE
Νοσηλευτές D1_1: Καρτέλα - Ο ασθενής δίνει ο ίδιος τα στοιχεία του

### ISSUE THREAD

**Issue by beieka** [eHIF/eHIFDemo#57]
Καρτέλα: Ο ασθενής δίνει ο ίδιος τα στοιχεία του
Δεν δίνεται η δυνατότητα εγγραφής νέου αριθμού ΑΜΚΑ. Μόνο όταν επιλεχθεί κάποιο άλλο ΑΜΚΑ από προηγούμενη εγγραφή, μπορεί να προχωρήσει η διαδικασία στο Επόμενο βήμα.

**Comment by larjohn** [comment]
Η διαδικασία προχωρά όταν το ΑΜΚΑ είναι 11 ψήφιο
