### ISSUE TITLE
KY_D2_1: Καρτέλα - Έλεγχος αποστολής φαρμακείου και Έλεγχος ελείψεων

### ISSUE THREAD

**Issue by beieka** [eHIF/eHIFDemo#59]
KY_D2_1: Καρτέλα - Έλεγχος αποστολής φαρμακείου

1) Ο χρήστης επιλέγει: ανάγκη προμήθειας φαρμακευτικού υλικού 
2) Ο χρήστης συμπληρώνει διαδοχικά όλα τα πεδία στις ενδιάμεσες καρτέλες 
3) Ο χρήστης φθάνει στην τελική καρτέλα -Έλεγχος αποστολής φαρμακείου - απ' όπου επιλέγοντας το Επόμενο βήμα, οδηγείται στο μενού Διαδικασίες.

KY_D2_1: Καρτέλα - Έλεγχος ελείψεων
Επίσης, στο πεδίο ΑΞΙΟΛΟΓΗΣΗ ΚΑΤΑΣΤΑΣΗΣ ΦΑΡΜΑΚΕΥΤΙΚΟΥ ΥΛΙΚΟΥ, κατά την επιλογή απόριψη δήλωσης, ο χρήστης οδηγείται στο μενού Διαδικασίες.

Μήπως θα έπρεπε ο χρήστης να οδηγείται πρώτα στην Καρτέλα Τέλος Διαδικασίας, όπως στις υπόλοιπες εφαρμογές?? και στη συνέχεια να οδηγείται στο κεντρικό μενού??

**Comment by larjohn** [comment]
Διορθώθηκε
