### ISSUE TITLE
Κέντρο Υγείας/ Διαδικασίες D1_1/ Εισαγωγή ασθενούς

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#60]
Δεν υπάρχει το κουμπί της ακύρωσης σε αυτήν την διαδικασία

**Comment by larjohn** [comment]
Link?

**Comment by kalkal1** [comment]
http://147.102.33.146/eHIFDemo/public/bpmn/runtime/D1_1:1:7504/usertask5/23469
Κέντρο Υγείας/Διαδικασίες/D1_1/Εισαγωγή ασθενούς/Καταγραφή δεδομένων ασθενή/Ο ασθενής δίνει ο ίδιος τα στοιχεία του
(Στο βήμα της αναζήτησης ασθενούς).

**Comment by larjohn** [comment]
Διορθώθηκε και θα υποβληθεί
