### ISSUE TITLE
Πρόβλημα στο «Συνεδρίες με τον Ιατρό»

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#61]
a.	Δεν μπορώ να καταλάβω πώς καταχωρείται μια καινούρια συνεδρία με τον ιατρό.
b.	Ο ασθενής kal έχει μπει στο ιατρείο, οπότε στην καρτέλα «Επισκέψεις στο Κέντρο Υγείας» εμφανίζεται πως ο kal είναι στο ιατρείο.
c.	Ωστόσο, στην καρτέλα «Συνεδρίες με τον Ιατρό» δεν μπορώ να βρω πουθενά την ασθενή kal, ακόμα και όταν έκλεισα την επίσκεψη της ασθενούς στην καρτέλα επισκέψεις.
d.     Υπάρχει κάποιος άλλος τρόπος για να καταχωρηθεί μια συνεδρία;

**Comment by larjohn** [comment]
Διορθώθηκε
