### ISSUE TITLE
Πρόβλημα στο  D1_1 Εισαγωγή ασθενούς Καταγραφή δεδομένων ασθενή

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#62]
login nosokomos--
Κέντρο Υγείας/Διαδικασίες D1_1/ Εισαγωγή ασθενούς/ Καταγραφή δεδομένων ασθενή/ Ο ασθενής δίνει ο ίδιος τα στοιχεία του

Στο βήμα αυτό αν ψάξω έναν καταχωρημένο ασθενή (πχ Ασθένιος) και μετά πατήσω πάνω στον ασθενή που δείχνει το αποτέλεσμα της αναζήτησης δεν συμπληρώνεται η αποκάτω φόρμα με τα στοιχεία του ασθενούς. Δεν ξέρω αν είναι θέμα browser.. αλλά το δοκίμασα και σε άλλον και το πρόβλημα παραμένει.

**Comment by larjohn** [comment]
Διορθώθηκε
