### ISSUE TITLE
Κέντρο Υγείας/Διαδικασίες D1_3/Ο ιατρός του ΚΥ αποφασίζει αν θα φτιαχτεί Ατομικός Ιατρικός Φάκελος/Δημιουργία φακέλου από τον ιατρό

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#63]
a.	O αύξων αριθμός δεν πρέπει να δίνεται από το σύστημα; Σαν πεδίο εξυπηρετεί κάτι;
b.	Στο τέλος της διαδικασίας αυτής και αφού έχω επιλέξει προσωρινή παραμονή παρουσιάζεται σφάλμα. (Αφού πατήσω Επόμενο στο βήμα Ο ιατρός του Κέντρου Υγείας κρίνει ότι απαιτείται η παραμονή του ασθενούς για βραχύχρονη φιλοξενία στο ΚΥ)
c.	Μετά το τέλος της διαδικασίας δεν έχει ενημερωθεί ο  ιατρικός φάκελος του ασθενούς. Πχ η Διεύθυνση δεν έχει περαστεί στον αντίστοιχο ασθενή στην καρτέλα Ασθενείς. Ομοίως και το έτος γέννησης που δίδεται σαν string στο βήμα Δημιουργία φακέλου από τον ιατρό, ενώ στην καρτέλα Ασθενείς είναι με μορφή ημερομηνίας.
d.	Τα ευρήματα της εξέτασης κατά την εκτέλεση αυτής της διαδικασίας θα έπρεπε να περαστούν στον ιστορικό του ασθενούς (στην αντίστοιχη συνεδρία). Ωστόσο, μετά το τέλος της διαδικασίας κανένα σύμπτωμα που είχε επιλεχτεί από την λίστα, ούτε κανένα από τα σχόλια δεν έχουν περαστεί στην αντίστοιχη καρτέλα της συνεδρίας. 
 ( Κέντρο Υγείας/ Διαδικασίες    D1_3/Ο ιατρός του ΚΥ αποφασίζει αν θα φτιαχθεί Ατομικός Ιατρικός Φάκελος/Δημιουργία φακέλου από τον ιατρό/Ο ιατρός καταγράφει τα ευρήματα της εξέτασης/Στον ιατρικό φάκελο μπορούν να επισυναφθούν τα αποτελέσματα των εξετάσεων)--Δεν καταγράφηκαν τα ευρήματα της εξέτασης και τα αποτελέσματα των εξετάσεων στο ιστορικού του ασθενούς
e.	Το ίδιο παρατηρείται ακόμα και αν ο γιατρός συνταγογραφήσει εξετάσεις, αυτές δεν έχουν περαστεί στα αντίστοιχα πεδία στην συνεδρία

**Comment by larjohn** [comment]
a. duplicate 
b. duplicate #58

**Comment by larjohn** [comment]
Όταν λέτε "τέλος της διαδικασίας" ποιο είναι το τελευταίο βήμα εκτέλεσης αυτής;

**Comment by kalkal1** [comment]
Το ακριβές path είναι: 
Κέντρο Υγείας\ Διαδικασίες\ D1_9\ Ο ιατρός του Κέντρου Υγείας κρίνει ότι απαιτείται η παραμονή του ασθενούς για βραχύχρονη φιλοξενία στο ΚΥ.

**Comment by larjohn** [comment]
c. Η διεύθυνση προστέθηκε στην καρτέλα ασθενούς. Το έτος γέννησης είναι λάθος σαν προσέγγιση στη διαδικασία και θα διορθωθεί σε ημερομηνία @giannispappas

**Comment by larjohn** [comment]
d. Διορθώθηκε

**Comment by larjohn** [comment]
e. Διορθώθηκε
