### ISSUE TITLE
Απουσία εμφάνισης  ροής διαδικασιών από login nosokomos σε iatros

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#67]
a. Ορισμένες διαδικασίες εκκινούνται από τον nosokomo και από ένα σημείο και μετά θα πρέπει να εμφανίζονται σε άλλους χρήστες (από το σημείο που έχει σταματήσει ο nosokomos). Ωστόσο, ακόμα και αν ο nosokomos ξεκινήσει μια διαδικασία αυτή δεν είναι ορατή στους υπόλοιπους χρήστες.
b.	Πχ D1_7:Παράδοση εσωτερικού παραπεμπτικού στον διοικητικό υπάλληλο (δεν είναι ορατή στον διοικητικό υπάλληλο ακόμα και αν τελειώσει η διαδικασία)
http://147.102.33.146/eHIFDemo/public/bpmn/runtime/D1_7:1:7533/usertask1/26899
c.	Κέντρο Υγείας/Διαδικασίες D1_3/Ο ιατρός του ΚΥ αποφασίζει αν θα φτιαχθεί Ατομικός Ιατρικός Φάκελος/Δημιουργία φακέλου από τον ιατρό

**Comment by larjohn** [comment]
Διορθώθηκε - εμφανίζεται στο γραμματέα.

Το σφάλμα στη γραμματεία αναμένει δίορθωση εδώ: eHIF/processes#13
