### ISSUE TITLE
Πρόσβαση nosokomos σε όλες τις διαδικασίες από την αρχή μέχρι και το τέλος

### ISSUE THREAD

**Issue by kalkal1** [eHIF/eHIFDemo#68]
a.	Πχ στο βήμα Κέντρο Υγείας/Διαδικασίες D1_3/Ο ιατρός του ΚΥ αποφασίζει αν θα φτιαχθεί Ατομικός Ιατρικός Φάκελος/Δημιουργία φακέλου από τον ιατρό. Σε αυτό το βήμα μπορεί και έχει πρόσβαση κανονικά o nosokomos οπότε και μπορεί να φτιάξει κανονικά ιατρικό φάκελο. Γενικά έχει πρόσβαση σε όλες τις διαδικασίες από την αρχή μέχρι το τέλος τους.

**Comment by larjohn** [comment]
Επιλύθηκε
